### ISSUE TITLE
Easy access to Bearer Token

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus-explorer#18]
Currently, if you want to grab the ID of an entity that is now viewable publicly, you need to pass your bearer token in the HTTP header. In order to get your Bearer Token, you need (in Chrome for instance) to open the Developer Tools > Network then reload the page and browse element, select one and open the HTTP headers tab to grab the token.

Instead of that, could the token be made available through the top right user panel ? For instance upon clicking on the user's name, open a panel where one could copy the token to the clipboard. That Panel could also show the list of groups the user is part of and other useful info the token contains as can be decoded on https://jwt.io/

**Comment by kenjinp** [comment]
resolved as of version 0.4.7

I've put a button in the top-right header. 
![screen shot 2018-08-20 at 13 53 04](https://user-images.githubusercontent.com/5485824/44339124-82154000-a480-11e8-9eeb-747a96f1ff4f.png)
