### ISSUE TITLE
Explorer login error: "String contains invalid character"

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-explorer#20]
@wizmer tried to login to the explorer but received the above pasted error. We suspect it has to do with the fetching of his name because it contains an accent circonflexe on the "i"

**Comment by mdupont** [comment]
@annakristinkaufmann @wizmer Can we get in touch so that I can copy the token value on which the code is failing? My name contains "ë" and the login works just fine.

**Comment by mdupont** [comment]
There was an issue with token decoding, fixed in v0.4.2 which is now deployed in staging and production.
