### ISSUE TITLE
The json inspector for instance views shows contaminated data!

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-explorer#21]
There's some data in the JSON inspector that isn't in the actual nexus payload. I guess the object is being mutated for UI purposes. 

- metafields
- resolvedLinks
- numFields

![screen shot 2018-08-20 at 13 57 57](https://user-images.githubusercontent.com/5485824/44339326-357e3480-a481-11e8-8eeb-a05822732609.png)

**Comment by mdupont** [comment]
Fixed in 0.4.8
