### ISSUE TITLE
Text search is basically useless :(

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-explorer#31]
you cannot search for name or type

**Comment by umbreak** [comment]
For searches on specific parameters rather use the filter API
```json
{
  "op": "eq",
  "path": "rdf:type",
   "value": "{value}"
}
```

In any case, can you give some precise examples of the API calls you are doing?

**Comment by kenjinp** [comment]
using full text search: https://bbp-nexus.epfl.ch/staging/v0/data?from=0&q=tkb0%2A&size=20 and appending a *

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#159
