### ISSUE TITLE
Show logged-out message if token expires

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-explorer#5]

**Comment by kenjinp** [comment]
![screen shot 2018-08-20 at 13 47 33](https://user-images.githubusercontent.com/5485824/44339024-2945a780-a480-11e8-9931-0a0927144546.png)

when the token is expired only a unending loading message is dispalyed

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#139
